---
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
      - run: npm run format
      - uses: fregante/setup-git-user@v1
      - if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          # commit only if there is a diff
          if ! git diff --exit-code; then
            git add .
            git commit -m "chore: compile and lint $GITHUB_SHA [ci skip]"
            git push origin main
          fi
